package com.example.hello_selenium_junit;
// Generated by Selenium IDE
        import static org.hamcrest.CoreMatchers.is;
        import static org.hamcrest.core.IsNot.not;

        import org.junit.jupiter.api.AfterEach;
        import org.junit.jupiter.api.BeforeEach;
        import org.junit.jupiter.api.Test;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.chrome.ChromeOptions;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.firefox.FirefoxOptions;
        import org.openqa.selenium.opera.OperaOptions;
        import org.openqa.selenium.remote.RemoteWebDriver;
        import org.openqa.selenium.remote.DesiredCapabilities;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.interactions.Actions;
        import org.openqa.selenium.support.ui.ExpectedConditions;
        import org.openqa.selenium.support.ui.WebDriverWait;
        import org.openqa.selenium.JavascriptExecutor;
        import org.openqa.selenium.Alert;
        import org.openqa.selenium.Keys;

        import javax.security.auth.login.Configuration;
        import java.time.Duration;
        import java.util.*;
        import java.net.MalformedURLException;
        import java.net.URL;

public class SearchROperaTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() throws MalformedURLException{
        OperaOptions operaOptions = new OperaOptions();
        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"), operaOptions);

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchdevops() throws InterruptedException{

        // Test name: search-devops
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.google.com/");
        // 2 | selectFrame | index=0 |
        driver.switchTo().frame(0);
        // 3 | click | css=#introAgreeButton .RveJvd |
        driver.findElement(By.cssSelector("#introAgreeButton .RveJvd")).click();
        // 4 | selectFrame | relative=parent |
        driver.switchTo().defaultContent();
        // 5 | click | name=q |
        driver.findElement(By.name("q")).click();
        // 6 | type | name=q | devops
        driver.findElement(By.name("q")).sendKeys("devops");
        // 7 | sendKeys | name=q | ${KEY_ENTER}
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        // 8 | click | css=.g:nth-child(10) .LC20lb > span |
        WebElement googleresult = new WebDriverWait(driver,20)
                .until(driver -> driver.findElement(By.xpath("//div[@id=\'rso\']/div[3]/div/div/a/h3/span")));
        driver.findElement(By.xpath("//div[@id=\'rso\']/div[3]/div/div/a/h3/span")).click();
    }

}


