package com.example.hello_selenium_junit;
// Generated by Selenium IDE
    import static org.hamcrest.CoreMatchers.is;
    import static org.hamcrest.core.IsNot.not;

    import org.junit.jupiter.api.AfterEach;
    import org.junit.jupiter.api.BeforeEach;
    import org.junit.jupiter.api.Test;
    import org.openqa.selenium.By;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.firefox.FirefoxDriver;
    import org.openqa.selenium.chrome.ChromeDriver;
    import org.openqa.selenium.remote.RemoteWebDriver;
    import org.openqa.selenium.remote.DesiredCapabilities;
    import org.openqa.selenium.Dimension;
    import org.openqa.selenium.WebElement;
    import org.openqa.selenium.interactions.Actions;
    import org.openqa.selenium.support.ui.ExpectedConditions;
    import org.openqa.selenium.support.ui.WebDriverWait;
    import org.openqa.selenium.JavascriptExecutor;
    import org.openqa.selenium.Alert;
    import org.openqa.selenium.Keys;

    import java.time.Duration;
    import java.util.*;
    import java.net.MalformedURLException;
    import java.net.URL;

public class SearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchdevops() throws InterruptedException {
        // Test name: search-devops
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.google.com/");
        // 2 | selectFrame | index=0 |
        driver.switchTo().frame(0);
        // 3 | click | css=#introAgreeButton .RveJvd |
        driver.findElement(By.cssSelector("#introAgreeButton .RveJvd")).click();
        // 4 | selectFrame | relative=parent |
        driver.switchTo().defaultContent();
        // 5 | click | name=q |
        driver.findElement(By.name("q")).click();
        // 6 | type | name=q | devops
        driver.findElement(By.name("q")).sendKeys("devops");
        // 7 | sendKeys | name=q | ${KEY_ENTER}
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        // 8 | click | css=.g:nth-child(10) .LC20lb > span |
        //driver.findElement(By.xpath("//div[@id=\'rso\']/div[3]/div/div/a/h3/span")).click();
        WebElement googleresult = new WebDriverWait(driver,7)
                .until(driver -> driver.findElement(By.xpath("//div[@id=\'rso\']/div[3]/div/div/a/h3/span")));
        driver.findElement(By.xpath("//div[@id=\'rso\']/div[3]/div/div/a/h3/span")).click();
    }

}
